name: ArtixDuels
version: '${project.version}'
description: 'ArtixDuels'
authors: [ 'Faastyzin' ]
website: 'https://store.artixdevelopment.com'
main: dev.artix.artixduels.ArtixDuels
api-version: 1.13
